
stages:
  - build
  - deploy

cache:
  paths:
    - .nuxt
    - node_modules

before_script:
  - hostname
  - node -v
  - npm -v
  - git --version
  - yarn

编译:
  stage: build
  script:
    - yarn build
  only:
    - master
  except:
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedules
    - triggers
    # - web

部署:
  stage: deploy
  script:
    - pm2 delete blog
    - pm2 start npm --name 'blog' -- start
  only:
    - master
  except:
    - tags
    - api
    - external
    - pipelines
    - pushes
    - schedules
    - triggers
    # - web